# Generated by Django 4.1.7 on 2023-06-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0006_rename_message_messagenormalroom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grouproom",
            name="amout_of_users",
            field=models.IntegerField(default=0),
        ),
    ]
